# Site settings
title: mr.colson
email: mrcolson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website of Doug Olson, also known as mr. colson. This site documents my activities as a music producer, mixer, engineer and audio editor, 
  both as a freelancer and at Smart Studios in Madison, Wisconsin, where I worked with Butch Vig, Steve Marker and Doug Ericson from 1987 through 2004. The site also pertains to my activities as an instructor and program chair for recording 
  and music technology at the Madison Media Institute, where I teach Pro Tools, studio recording, audio engineering, audio editing, audio mixing techniques and electronics.  
baseurl: #/blog/
url: http://www.mrcolson.com
#twitter_username: twitter_username
github_username:  dougolson

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap
  
collections:
  portfolio:
    output: true
    permalink: /discography/:path/
  projects:
    output: true
    permalink: /projects/:path/



