# Site settings
title: mr.colson
email: mrcolson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  doug olson's website'
baseurl: #/blog/
url: http://www.mrcolson.com
#twitter_username: twitter_username
github_username:  dougolson

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap
  
collections:
  portfolio:
    output: true
    permalink: /discography/:path/
  projects:
    output: true
    permalink: /projects/:path/



