# Site settings
title: mr.colson
email: mrcolson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Doug Olson, professionally known as mr. colson. I am a music producer, mixer, audio engineer and audio editor. I have worked as a freelancer and at Smart Studios in Madison, Wisconsin, 
  where I worked with Butch Vig, Steve Marker, Mark Haines, Doug Ericson and many others from 1987 through 2004. I am also an instructor and program chair for recording 
  and music technology at the Madison Media Institute, where I teach Pro Tools, studio recording, recording techniques, audio engineering, audio editing, audio mixing techniques and electronics.  
baseurl: #/blog/
url: http://www.mrcolson.com
#twitter_username: twitter_username
github_username:  dougolson

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap
  
collections:
  portfolio:
    output: true
    permalink: /discography/:path/
  projects:
    output: true
    permalink: /projects/:path/



